#!/usr/bin/env python3
"""Exact-image offline probes for recorder settings and post-selection gain."""
import argparse
from pathlib import Path
import struct

from emulate_platform import APP_BASE, SOURCE, STACK, inputs
from firmware import digest, revision
from native_receive import Isolated, tool_hashes as receive_hashes
from recorder_interface import identity
from reporting import atomic_json

TABLE = 0x20190ecc
SETTINGS = {35: 'RF/SQL Control', 287: 'REC Mode', 288: 'TX REC Audio',
            289: 'RX REC Condition', 290: 'File Split'}
STATE = 0x2039041c
SCRATCH = 0x203fc76c


def setting_probe(app, index):
    if type(index) is not int or index not in SETTINGS:
        raise ValueError('Require a reviewed setting index')
    rows = []
    for language in (0, 1):
        h = Isolated(app, [(0x20086000, 0x20086098)], [(SOURCE, 12)])
        h.uc.mem_write(SOURCE, bytes(8)+struct.pack('<BBH', 2, 0, index))
        row = h.run(0x20086000, (SOURCE, language, 0, 0))
        fields = struct.unpack_from('<16I', app, TABLE+index*64-APP_BASE)
        if row['r0'] != fields[10+language*3] or any(a == h.u.UC_MEM_WRITE for a, _, _ in h.accesses):
            raise ValueError('Unexpected selector result or input write')
        rows.append(row['r0'])
    offset = rows[0]-APP_BASE
    label = app[offset:app.index(b'\0', offset)].decode('ascii')
    if label != SETTINGS[index]:
        raise ValueError('Unexpected setting label')
    return {'index': index, 'record': hex(TABLE+index*64), 'label': label,
            'value_pointer': hex(fields[0]), 'option_table': hex(fields[15]),
            'label_pointers': [hex(p) for p in rows]}


def route_probe(app, cases, samples):
    if not isinstance(samples, (list, tuple)) or len(samples) != 6 or any(
            type(x) is not int or not -32768 <= x <= 32767 for x in samples):
        raise ValueError('Require six signed PCM16 samples')
    if not isinstance(cases, (list, tuple)) or not cases or any(
            not isinstance(c, (list, tuple)) or len(c) != 3 or
            any(type(x) is not int for x in c) or c[0] not in (0, 1) or
            not 0 <= c[1] <= 255 or not 0 <= c[2] <= 255 for c in cases):
        raise ValueError('Require TX REC Audio, gate-byte and tag-byte fixtures')
    h = Isolated(app, [(0x20067328, 0x200673e4), (0x20049044, 0x2004909c),
                      (0x20020318, 0x20020324), (0x20066ed0, 0x20066f18), (0x2017c750, 0x2017c76a)],
                 [(0x20390282, 1), (0x203de70b, 1), (0x20390104, 1), (STATE, 10), (SCRATCH-2, 16)])
    rows = []
    for tx_audio, gate, tag in cases:
        h.uc.mem_write(0x203de70b, bytes([tx_audio]))
        h.uc.mem_write(0x20390104, bytes([gate]))
        h.uc.mem_write(0x20390282, bytes([tag]))
        h.uc.mem_write(STATE, bytes(10))
        h.uc.mem_write(SCRATCH-2, b'\xa5'*16)
        h.uc.mem_write(STACK+0xf008, struct.pack('<6h', *samples))
        h.uc.reg_write(h.a.UC_ARM_REG_R9, 0x20390282)
        h.uc.reg_write(h.a.UC_ARM_REG_R8, STATE)
        h.accesses.clear()
        result = h.run(0x20067328, stop=0x200673e4)
        writes = [(addr, size) for access, addr, size in h.accesses if access == h.u.UC_MEM_WRITE]
        if any(not ((addr == STATE+2 and size == 1) or
                    (SCRATCH <= addr and addr+size <= SCRATCH+12)) for addr, size in writes):
            raise ValueError('Unexpected recorder write footprint')
        guard = bytes(h.uc.mem_read(SCRATCH-2, 16))
        if guard[:2] != b'\xa5'*2 or guard[-2:] != b'\xa5'*2:
            raise ValueError('Recorder output guard changed')
        rows.append({'tx_rec_audio': tx_audio, 'gate_20390104': gate, 'tag': tag,
                     'output': list(struct.unpack('<6h', guard[2:14])),
                     'copy_mode': h.uc.reg_read(h.a.UC_ARM_REG_R7),
                     'instructions': result['instructions']})
    return rows


def tool_hashes():
    return dict(receive_hashes(), native_recorder_controls=digest(Path(__file__).read_bytes()))


def _report(image):
    data, _, app, _ = inputs(image)
    samples = [-32768, -257, -1, 0, 1, 32767]
    cases = [(t, g, tag) for t in (0, 1) for g in (0, 1, 255) for tag in range(256)]
    return {'image_sha256': digest(data), 'application_sha256': digest(app),
            'settings': [setting_probe(app, i) for i in SETTINGS], 'input_samples': samples,
            'routes': route_probe(app, cases, samples),
            'limits': ['Original post-selection code only; earlier recorder suppression gates are bypassed.',
                       'Gate byte is supplied, not generated by physical squelch or DSP state.',
                       'Numerical route tags do not establish physical RX/TX channel identity.',
                       'Settings selector executes original label lookup; UI writes and option-index rendering are not executed.',
                       'No radio, DMA, DSP, PTT or filesystem operation is executed by the probes.']}


def report(image):
    image = Path(image)
    initial, hashes, source = identity(image), tool_hashes(), revision()
    result = _report(image)
    if identity(image) != initial or result['image_sha256'] != initial[0] or hashes != tool_hashes() or source != revision():
        raise ValueError('Image/source changed during recorder control analysis')
    return dict(result, source_revision=source, tool_sha256=hashes, source_unchanged=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('image', type=Path)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    if args.output.exists():
        parser.error('Output already exists')
    result = report(args.image)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    atomic_json(args.output, result)
    print(args.output)


if __name__ == '__main__':
    main()
